# Generated by Django 4.2.3 on 2023-08-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livrobaptismo',
            old_name='fotoperfil',
            new_name='imagem',
        ),
    ]
