# Generated by Django 4.2.3 on 2023-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0002_rename_fotoperfil_livrobaptismo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registobaptismo',
            name='madrinhaprofissao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão da Madrinha'),
        ),
        migrations.AlterField(
            model_name='registobaptismo',
            name='padrinhoprofissao',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Profissão do Padrinho'),
        ),
    ]
