# Generated by Django 4.2.3 on 2023-07-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0002_livrobaptismo_nome_livrocasamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registocasamento',
            name='igreja',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='chancelaria.paroquia', verbose_name='Igreja'),
        ),
    ]
