# Generated by Django 4.2.3 on 2023-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0003_alter_registobaptismo_madrinhaprofissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registobaptismo',
            name='folha',
            field=models.CharField(default=123, max_length=4, unique=True, verbose_name='Fl'),
            preserve_default=False,
        ),
    ]
