# Generated by Django 4.2.3 on 2023-08-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0004_registobaptismo_folha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livrocasamento',
            old_name='fotoperfil',
            new_name='imagem',
        ),
    ]
