# Generated by Django 4.2.3 on 2023-08-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0005_rename_fotoperfil_livrocasamento_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livrocasamento',
            options={'verbose_name': 'Registos de Duplicados de Casamento'},
        ),
        migrations.RemoveField(
            model_name='livrocasamento',
            name='ano',
        ),
    ]
