# Generated by Django 4.2.3 on 2023-08-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0006_alter_livrocasamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicadosCasamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Descrição')),
                ('datainicio', models.DateField(help_text='formato da data: 2000-01-01', verbose_name='Data do inicio')),
                ('datafim', models.DateField(verbose_name='Data do encerramento')),
                ('imagem', models.ImageField(height_field=150, help_text='Imagem Para Capa do Livro', upload_to='imgagem_capa', verbose_name='Imagem de Capa', width_field=150)),
                ('diocese', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='chancelaria.diocese', verbose_name='Diocese de proveniencia')),
                ('paroquia', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='chancelaria.paroquia', verbose_name='Paróquia de proveniencia')),
                ('provincia', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='chancelaria.provincia', verbose_name='Província de proveniencia')),
            ],
            options={
                'verbose_name': 'Registos de Duplicados de Casamento',
            },
        ),
    ]
