# Generated by Django 4.2.3 on 2023-08-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0007_duplicadoscasamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livrobaptismo',
            options={'verbose_name': 'Livro de registos do Casamento'},
        ),
    ]
