# Generated by Django 4.2.3 on 2023-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0009_alter_livrobaptismo_options_livrocasamentoduplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrocasamentoduplicado',
            name='numero',
        ),
        migrations.AlterField(
            model_name='livrocasamentoduplicado',
            name='datainicio',
            field=models.DateField(help_text='formato da data: 2000-01-01', verbose_name='Data do inicio'),
        ),
    ]
