# Generated by Django 4.2.3 on 2023-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0010_remove_livrocasamentoduplicado_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=9, null=True, unique=True, verbose_name='Telefone'),
        ),
    ]
