# Generated by Django 4.2.3 on 2023-08-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0014_alter_paroquia_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registocasamento',
            name='Livro',
            field=models.ForeignKey(default=55, max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.duplicadoscasamento', verbose_name='Livro'),
            preserve_default=False,
        ),
    ]
