# Generated by Django 4.2.3 on 2023-08-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0015_registocasamento_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registocasamento',
            name='Livro',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.livrocasamentoduplicado', verbose_name='Livro'),
        ),
    ]
