# Generated by Django 4.2.3 on 2023-08-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0017_alter_livrocasamentoduplicado_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='livroCasamento',
        ),
    ]
