# Generated by Django 4.2.3 on 2023-08-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0018_delete_livrocasamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registobaptismo',
            old_name='estadocivilapai',
            new_name='estadocivilpai',
        ),
    ]
