# Generated by Django 4.2.3 on 2023-08-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0020_rename_resindeciapai_registobaptismo_resideciapai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registobaptismo',
            old_name='residenciamae',
            new_name='resideciamae',
        ),
    ]
