# Generated by Django 4.2.3 on 2023-08-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0022_rename_resideciapai_registobaptismo_residenciapai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registobaptismo',
            old_name='resideciamae',
            new_name='residenciamae',
        ),
    ]
