# Generated by Django 4.2.3 on 2023-08-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0024_alter_livrobaptismo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registobaptismo',
            name='estadocivilmae',
            field=models.CharField(blank=True, choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=150, null=True, verbose_name='Estado civil da Mãe'),
        ),
        migrations.AlterField(
            model_name='registobaptismo',
            name='estadocivilpai',
            field=models.CharField(blank=True, choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=150, null=True, verbose_name='Estado civil do Pai'),
        ),
        migrations.AlterField(
            model_name='registobaptismo',
            name='madrinhaestadocivil',
            field=models.CharField(blank=True, choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=150, null=True, verbose_name='Estado cilvil da Madrinha'),
        ),
        migrations.AlterField(
            model_name='registobaptismo',
            name='padrinhoestadocivil',
            field=models.CharField(blank=True, choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=15, null=True, verbose_name='Estado civil do Padrinho'),
        ),
        migrations.AlterField(
            model_name='registocasamento',
            name='estadocivilnoiva',
            field=models.CharField(choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=14, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='registocasamento',
            name='estadocivilnoivo',
            field=models.CharField(choices=[('Casado (a)', 'Casado (a)'), ('Soteiro (a)', 'solteiro (a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado (a)', 'Divorciado (a)')], max_length=14, verbose_name='Estado Civil'),
        ),
    ]
