# Generated by Django 4.2.3 on 2023-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0026_alter_registobaptismo_estadocivilmae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='fotoperfil',
            field=models.FileField(upload_to='img_perfil_centro', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='fotoperfil',
            field=models.FileField(upload_to='imf_perfil_congregacao', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='fotoperfil',
            field=models.FileField(upload_to='img_perfil_diocese', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='livrobaptismo',
            name='imagem',
            field=models.FileField(help_text='Imagem Para Capa do Livro', upload_to='imgagem_capa', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='livrocasamentoduplicado',
            name='imagem',
            field=models.FileField(help_text='Imagem Para Capa do Livro', upload_to='imgagem_capa', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='fotoperfil',
            field=models.FileField(upload_to='img_perfil_paroquia', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='registocasamento',
            name='imagemfrente',
            field=models.FileField(upload_to='img_assento_casamento', verbose_name='Imagem Frente'),
        ),
        migrations.AlterField(
            model_name='registocasamento',
            name='imagemverso',
            field=models.FileField(upload_to='img_assento_casamento', verbose_name='Imagem Verso'),
        ),
    ]
