# Generated by Django 4.2.3 on 2023-08-18 10:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0028_alter_registobaptismo_madrinha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('nome', models.CharField(blank=True, default='Insira o seu nome', help_text='Isso ajudará os seu amigos na pesquisa', max_length=200, null=True, verbose_name='Nome completo')),
                ('pai', models.CharField(blank=True, default='Insira o nome do seu progenitor', help_text='Esta campo fica pode ser util', max_length=200, null=True, verbose_name='Pai')),
                ('mae', models.CharField(blank=True, default='Insira o nome da sua progenitora', help_text='Esta campo fica pode ser util', max_length=200, null=True, verbose_name='Mãe')),
                ('bi', models.CharField(default='Insira o nome da sua progenitora', help_text='Ela servirá como o seu identidicador', max_length=200, primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='Endereço')),
                ('nurural', models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='Província, Cidade ou Estado')),
                ('nascimento', models.DateField(help_text='2000-01-01', verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('nacionalidade', models.CharField(default='Angolana', max_length=10, verbose_name='Nacionalidade')),
                ('estadocivil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Soteiro(a)', 'solteiro(a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=14, verbose_name='Estado civil')),
                ('provincia', models.ForeignKey(blank=True, default=' ', max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.provincia', verbose_name='Província')),
            ],
        ),
    ]
