# Generated by Django 4.2.3 on 2023-08-18 13:29

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0029_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='imagem',
            field=models.FileField(blank=True, default='serra.jpg', null=True, upload_to='img_perfil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bi',
            field=models.CharField(default=' ', help_text='Ela servirá como o seu identidicador', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(blank=True, default=' ', help_text='Esta campo fica pode ser util', max_length=200, null=True, verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, default=' ', help_text='Isso ajudará os seu amigos na pesquisa', max_length=200, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(blank=True, default=' ', help_text='Esta campo fica pode ser util', max_length=200, null=True, verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pais',
            field=django_countries.fields.CountryField(default='Angola', max_length=2, verbose_name='Páis'),
        ),
    ]
