# Generated by Django 4.2.3 on 2023-08-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0030_pessoa_imagem_alter_pessoa_bi_alter_pessoa_mae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='provincia',
            field=models.ForeignKey(blank=True, default=' ', max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.provincia', verbose_name='Província ou Estado'),
        ),
    ]
