# Generated by Django 4.2.3 on 2023-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0031_alter_pessoa_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registobaptismo',
            name='municipio',
            field=models.CharField(blank=True, default='..........', max_length=100, null=True),
        ),
    ]
