# Generated by Django 4.2.3 on 2023-08-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0033_alter_registobaptismo_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='registobaptismo',
            name='madrinharesidencia',
            field=models.CharField(blank=True, default='..........', max_length=150, null=True, verbose_name='Residencia'),
        ),
        migrations.AddField(
            model_name='registobaptismo',
            name='padrinhoresidencia',
            field=models.CharField(default='..........', max_length=15, null=True, verbose_name='Residencia'),
        ),
        migrations.AlterField(
            model_name='registobaptismo',
            name='padrinhoprofissao',
            field=models.CharField(default='..........', max_length=15, null=True, verbose_name='Profissão do Padrinho'),
        ),
    ]
