# Generated by Django 4.2.3 on 2023-08-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0034_registobaptismo_madrinharesidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssentoDeObito',
            fields=[
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo do malogrado')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=14)),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora da morte')),
                ('sacramentos', models.CharField(choices=[('B', 'Baptismo'), ('BC', 'Baptismo e Comunhão'), ('BCC', 'Baptismo, Comunhão e Crisma'), ('BCCC', 'Baptismo, Comunhão, Crisma e Matrimonio'), ('BCCS', 'Baptismo, Comunhão, Crisma e Matrimonio')], default='Sem sacremento', max_length=100)),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('data', models.DateField(verbose_name='Data')),
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('estadocivil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Soteiro(a)', 'solteiro(a)'), ('Viùvo(a)', 'Viùvo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=14, verbose_name='Estado Civil')),
                ('conjuge', models.CharField(blank=True, default='.........', max_length=100, null=True, verbose_name='Cônjuge')),
                ('endereco', models.CharField(blank=True, default='.........', max_length=100, null=True, verbose_name='Endereço')),
                ('nomepai', models.CharField(blank=True, default='..........', max_length=100, null=True, verbose_name='Nome do Pai')),
                ('provinciapai', models.CharField(blank=True, default='..........', max_length=100, null=True, verbose_name='Naturalidade do Progenitor')),
                ('nomemae', models.CharField(blank=True, default='..........', max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('provinciamae', models.CharField(blank=True, default='..........', max_length=100, null=True, verbose_name='Naturalidade da Mãe')),
                ('paroco', models.CharField(default='..........', max_length=100)),
                ('imagem', models.FileField(upload_to='imagem_obito')),
                ('arquidiocese', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.arquidiocese')),
                ('paroquia', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.paroquia')),
                ('provincia', models.ForeignKey(blank=True, default='.........', max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chancelaria.provincia', verbose_name='Província')),
            ],
        ),
    ]
