# Generated by Django 4.2.3 on 2023-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0035_assentodeobito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrocasamentoduplicado',
            name='id',
        ),
        migrations.AddField(
            model_name='livrocasamentoduplicado',
            name='numero',
            field=models.IntegerField(default=111, primary_key=True, serialize=False, verbose_name='Livro nº'),
            preserve_default=False,
        ),
    ]
