# Generated by Django 4.2.3 on 2023-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancelaria', '0036_remove_livrocasamentoduplicado_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrocasamentoduplicado',
            name='numero',
        ),
        migrations.AddField(
            model_name='livrocasamentoduplicado',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
